In [1]:
## preload numpy
import numpy as np

## Create RNG generator
rng = np.random.default_rng()
try:
    rng_integers = rng.integers
except AttributeError:
    rng_integers = rng.randint

In [2]:
## helper functions
def _rng_int_stream(low=0, high=100, count=10):
    """
        Return a stream of random integers
        low: the min integer to generate from pool (inclusive)
        high: the max integer to generate from pool (exclusive)
        count: the number of integers to generate
        method: how to provide the values back to the calling function
            - list: return a list() to the caller
            - yield: return values using the yield keyword
    """
    # coerce arguments to int()
    low, high, count = [int(x) for x in [low, high, count]]
    for _ in range(0,count):
        yield rng_integers(low,high)

def rng_int_iter(low=0, high=100, count=10):
    return list(_rng_int_stream(low, high, count))

def rng_int_gen(low=0, high=100, count=10):
    return _rng_int_stream(low, high, count)

def npa_details(npa):
    dic = {
        'type': type(npa),
        'ndim': npa.ndim,
        'shape': npa.shape,
        'size': npa.size,
        'dtype': npa.dtype,
        'itemsize': npa.itemsize,
        'nbytes': npa.nbytes,
        'data': npa.data,
    }
    for k,v in dic.items():
        print(f"The {k} of the numpy array is: {v}")
    print(f"print(np_array): {npa}")
    return dic

In [3]:
## preload some sample arrays
np1d = np.arange(20)
np2d = np.arange(20).reshape(4,5)
np3d = np.arange(27).reshape(3,3,3)

## preload some sample arrays with random data
np1d = np.fromiter(rng_int_iter(10,100,20), int, 20)
np2d = np.fromiter(rng_int_iter(10,100,20), int, 20).reshape(4,5)
np3d = np.fromiter(rng_int_iter(10,100,27), int, 27).reshape(3,3,3)

# NumPy arrays
NumPy’s array class is called `ndarray`. It is also known by the alias `array`. Note that `numpy.array` is not the same as the Standard Python Library class `array.array`, which only handles one-dimensional arrays and offers less functionality.

## Instantiating an ndarray
```py
import numpy as np
np_array = np.array([1, 2, 3, 5, 7, 11, 13, 17])
```

## Attributes
The more important attributes of an ndarray object are:
* ndim: the number of dimenions (axes) of the array
* shape: the dimensions of the array
* size: the total number of elements
* dtype: an object describing the type of the elements in the array
* itemsize: the size in bytes of each element in the array
* nbytes: the total size in bytes of the array
* data: the buffer containg the actual elements of the array


In [4]:
#Exploring numpy arrays attributes
_ = npa_details(np1d)
print()
_ = npa_details(np2d)
print()
_ = npa_details(np3d)
print()

The type of the numpy array is: <class 'numpy.ndarray'>
The ndim of the numpy array is: 1
The shape of the numpy array is: (20,)
The size of the numpy array is: 20
The dtype of the numpy array is: int32
The itemsize of the numpy array is: 4
The nbytes of the numpy array is: 80
The data of the numpy array is: <memory at 0x000002086DBCDB80>
print(np_array): [14 61 61 90 33 37 20 54 69 15 15 45 66 43 73 45 92 69 79 67]

The type of the numpy array is: <class 'numpy.ndarray'>
The ndim of the numpy array is: 2
The shape of the numpy array is: (4, 5)
The size of the numpy array is: 20
The dtype of the numpy array is: int32
The itemsize of the numpy array is: 4
The nbytes of the numpy array is: 80
The data of the numpy array is: <memory at 0x000002086D884380>
print(np_array): [[85 26 28 23 75]
 [83 43 50 21 16]
 [95 66 48 14 74]
 [80 50 95 37 65]]

The type of the numpy array is: <class 'numpy.ndarray'>
The ndim of the numpy array is: 3
The shape of the numpy array is: (3, 3, 3)
The size of t